all:
	pdflatex preface.tex
	pdflatex numbers.tex
	pdftk preface.pdf An.pdf Ay.pdf Ba.pdf Bo.pdf BrJ.pdf BrP.pdf Ch.pdf De.pdf Ei.pdf Ga.pdf Go2.pdf Go.pdf Gr.pdf Gu.pdf Hu.pdf Ja.pdf Ji.pdf Lia.pdf Lis.pdf Mc.pdf Na.pdf Or.pdf Pa.pdf Pie.pdf Pio.pdf Pu.pdf Sh.pdf Su.pdf Tw.pdf Wel.pdf Wer.pdf Wu.pdf Zh.pdf cat output a.pdf
	pdftk a.pdf multistamp numbers.pdf output b.pdf


